### ISSUE TITLE
does not work with webdriver 4.0

### ISSUE THREAD

**Issue by parisholley** [webdriverio/wdio-sync#26]
see webdriverio/webdriverio#1063 for some background. it appears this line:

```
runInFiberContext(
                INTERFACES[this.config.mochaOpts.ui][2],
                this.config.beforeHook,
                this.config.afterHook,
                fnName
            )
```
is preventing tests promise chaining from working correctly

**Comment by christian-bromann** [comment]
can you provide a reproducible example?

**Comment by christian-bromann** [comment]
I was not able to reproduce this issue. Closing
