### ISSUE TITLE
0.5.10: executeHooksWithArgs(...).finally is not a function

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/wdio-sync#36]
The following test was working when I had wdio-sync 0.5.8.  I think 0.5.10 broke it.

```js
import {expect} from 'chai'
import Promise from 'bluebird'
import 'core-js'
import 'regenerator-runtime/runtime'

describe('integration test setup', () => {
  it('page loads with correct title', function () {
    browser.url(process.env.APP_URL)
    const title = browser.getTitle()
    expect(title).to.equal('jcore.io')
  })
})
```

Now with wdio-sync 0.5.10 I get the following error:

```
1) integration test setup page loads with correct title:
executeHooksWithArgs(...).finally is not a function
running phantomjs
TypeError: executeHooksWithArgs(...).finally is not a function
    at Context.<anonymous> (index.js:8:13)
    at new Promise (/usr/src/app/node_modules/core-js/modules/es6.promise.js:191:7)
```

**Comment by christian-bromann** [comment]
How do you use `wdio-sync`? It gets poly filled right here https://github.com/webdriverio/wdio-sync/blob/master/index.js#L4

**Comment by jedwards1211** [comment]
Ah, I was confused, looks like `executeHooksWithArgs` functions exist in a lot of various `wdio` packages

**Comment by jedwards1211** [comment]
I don't think my `webdriverio` version changed though, whereas I did get a new version of `wdio-sync` as a subdep.  I'll have to dig deeper...

**Comment by christian-bromann** [comment]
@jedwards1211 wdio-sync is only used by our framework adapters to make commands synchronous. I am not sure how you use it.

**Comment by jedwards1211** [comment]
Nevermind, my `webdriverio` version changed as well

**Comment by jedwards1211** [comment]
I posted an issue in `webdriverio`.  I included a diff of my `webdriverio` and `wdio*` dep versions
