### ISSUE TITLE
should hooks be getting called before/after async commands?

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/wdio-sync#38]
If I understand the code correctly, hooks won't get run around async commands.

`wrapCommand` is basically the identity function for async commands: https://github.com/webdriverio/wdio-sync/blob/master/index.js#L153

But for sync commands it calls hooks:
https://github.com/webdriverio/wdio-sync/blob/master/index.js#L199

Is this right?  I'm trying to work on an async-only version, and this seemed odd to me.

**Comment by christian-bromann** [comment]
> hooks won't get run around async commands.

Only beforeCommand and afterCommand hooks are being ignored in async mode. On the longterm I wanted to implement them in the WebdriverIO monad but it's super low priority.

**Comment by jedwards1211** [comment]
I guess I'll just have to hope that fibers gets deprecated and abandoned someday.

**Comment by christian-bromann** [comment]
Fibers has right now way more advantages compared to async/await. I love to write my test code fully synchronous. It provides super clear stacktraces and is easy to understand for non devs. We will see how JS evolves and how other opinions will shape the architecture of this project. I appreciate your opinion but truly believe that making anything more difficult and inconvenient makes it harder for others and that is not the intention I want to follow.

**Comment by sassda** [comment]
kind of resurrecting this, what's the status of beforeCommand and afterCommand in async mode? I tried and they don't seem to be called, is this still a low priority?

**Comment by christian-bromann** [comment]
> is this still a low priority?

Command hooks might be available in v5, any contributions are much appreciated

**Comment by jedwards1211** [comment]
Darn :wink:

**Comment by christian-bromann** [comment]
> I'm still hoping fibers in node eventually becomes a thing of the past

@jedwards1211 why do you think that? Fibers is beautiful and clears up all unnecessary `await`s in my code. In v5 there will be no need for you to install fibers. You can work with async/await and it will be the same API. However you will have tons of unnecessary async awaits in your code.

**Comment by fijijavis** [comment]
My biggest complaint against fibers is that I prevents me from running my Wdio tests in a pure Alpine Docker container.

**Comment by jedwards1211** [comment]
* Things like @fijijavis said happen
* the fact that Fibers will lag behind anytime there's a breaking change to the C++ API it uses.
* Fibers isn't supported in the browser so the code isn't isomorphic (I lived through the awkwardness this caused in Meteor).  Obviously there is no reason for webdriver code to be isomorphic (though code it sends to the browser to execute must use async functions instead of fibers), but I prefer to use/write various helper libraries like async throttling, data fetching, polling and so forth using async functions instead of fibers.
