### ISSUE TITLE
Show more informative stack trace 

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-sync#45]
_From @monolithed on January 25, 2017 10:54_

## The problem

**test.js**

```js
let page = require('./page');

describe('test', () => {
	it('test', () => page());
});
```

**page.js**

```js
module.exports = () => {
	browser.url('https://e.mail.ru/login');
	browser.alertText();
};
```

## Actual

```
[chrome #0-0] Session ID: ec6a556d-0074-4b8d-9f28-537090c1fd7d
[chrome #0-0] Spec: /test.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]       1) test
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 failing (6s)
[chrome #0-0]
[chrome #0-0] 1) test test:
[chrome #0-0] Timeout of 3000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
[chrome #0-0] Error: Timeout of 3000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
[chrome #0-0]     at Timeout.<anonymous> (/node_modules/mocha/lib/runnable.js:232:19)
[chrome #0-0]     at ontimeout (timers.js:365:14)
[chrome #0-0]     at tryOnTimeout (timers.js:237:5)
[chrome #0-0]     at Timer.listOnTimeout (timers.js:207:5)
[chrome #0-0]
```

## Expected

```
[chrome #0-0] Session ID: ec6a556d-0074-4b8d-9f28-537090c1fd7d
[chrome #0-0] Spec: /tests/1788/test.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]       1) test
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 failing (6s)
[chrome #0-0]
[chrome #0-0] 1) test test:
[chrome #0-0] Something about its real error and place
[chrome #0-0]     at module.exports (/page.js:3:8) 
[chrome #0-0]     at Context.it (/test.js:4:19)
```

## assert

```js
assert(0, 'Something went wrong');
```

```
[chrome #0-0] Something went wrong
[chrome #0-0] AssertionError: Something went wrong
[chrome #0-0]     at module.exports (/page.js:6:2)
[chrome #0-0]     at Context.it (/test.js:4:19)
[chrome #0-0]
```

## throw

```js
throw new Error('Something went wrong');
```

```
[chrome #0-0] Something went wrong
[chrome #0-0]     at module.exports (/page.js:3:8) 
[chrome #0-0]     at Context.it (/test.js:4:19)
[chrome #0-0]
```

## webdriverio api

```js
browser.alertText();
```

```
[chrome #0-0]     at Timeout.<anonymous> (/tests/1788/node_modules/mocha/lib/runnable.js:232:19)
[chrome #0-0]     at ontimeout (timers.js:365:14)
[chrome #0-0]     at tryOnTimeout (timers.js:237:5)
[chrome #0-0]     at Timer.listOnTimeout (timers.js:207:5)
```

## Environment

* WebdriverIO version: 4.0.0-4.6.2
* Selenium version: any
* Node.js version: 6-7
* Mocha version: 2-3

## Code To Reproduce Issue

[__test__.zip](https://github.com/webdriverio/webdriverio/files/729282/__test__.zip)

_Copied from original issue: webdriverio/webdriverio#1842_

**Comment by christian-bromann** [comment]
This is a timeout stack you are showing which comes from Mocha. It doesn't give me any information which line has caused the timeout to get triggered. There is probably a super hacky way to do this but I don't see the necessity to get there.

**Comment by monolithed** [comment]
@christian-bromann, the current problem is actual for all methods

**Comment by christian-bromann** [comment]
@monolithed can you be more specific. From what I see from the issue description you seem to find the stacktrace of timeout errors insufficient but there is no way to make them more descriptive. Which methods are you talking about?

**Comment by monolithed** [comment]
> Which methods are you talking about?

@christian-bromann, there is a hypothesis, the problem is actual for absolutely all the methods.


```js
module.exports = () => {
     browser.url('https://e.mail.ru/login');
     browser.waitForVisible('foo');
}
```

```js
let page = require('./page');

describe('test', () => {
    it('test', () => {
        page();
    });
});
```

```js
------------------------------------------------------------------
[chrome #0-0] Session ID: 44423b38-d8af-4eb8-bc5f-ae0c68a338d0
[chrome #0-0] Spec: /Users/a.abashkin/Downloads/1752/test.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]       1) test
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 failing (5s)
[chrome #0-0]
[chrome #0-0] 1) test test:
[chrome #0-0] element (foo) still not visible after 1000ms
[chrome #0-0] Error: element (foo) still not visible after 1000ms
[chrome #0-0]     at elements("foo") - isVisible.js:54:17
[chrome #0-0]     at isVisible("foo") - waitForVisible.js:37:22
[chrome #0-0]
```


Here is a minimal reproducible example [45.zip](https://github.com/webdriverio/wdio-sync/files/819360/45.zip)

**Comment by monolithed** [comment]
@christian-bromann, did you reproduce the problem?

**Comment by sknight80** [comment]
Do we have any update on this? I am facing this issue all the time and slowing down the debuging+fixing process.

**Comment by mherodev** [comment]
I was digging for a solution to this myself. In an older version of webdriverio I was getting `Cannot get "indexOf" of undefined` which came with a useful stacktrace, but no readable error. Not we have readable errors but no stacktrace.

This ticket should not be closed.

**Comment by christian-bromann** [comment]
@mherodev if you think there is still a problem please create a new issue with a reproducible example

**Comment by miroslawmajka** [comment]
I can't remember exactly when but the stack traces in WebdriverIO became unusable with a certain version some time last year. Very minimal output and this means having to look and guess through several paths before we find why a test fails.

**Comment by sknight80** [comment]
I solved this problem with each Page Object in my test code has a wrapper with try-catch, and if there is an error, the wrapper throws an error including the WDIO error as well.  So in that case, I know which spec file, which line from the spec file and which method in a page object is failed.  With the WDIO error, I can narrow down the real step inside the Page Object method.  I know this solution is not that nice, but it is working for us, most of the time.

**Comment by zewa666** [comment]
@sknight80 mind sharing an example? Ideally there could be a nice helperfunction reducing the boilerplate

**Comment by sknight80** [comment]
Hi @zewa666, Sure. I will include it tomorrow or after tomorrow.
