### ISSUE TITLE
If fiber fails, command result does not get prototype applied

### ISSUE THREAD

**Issue by billyvg** [webdriverio/wdio-sync#46]
When this happens, `commandPromise` does not get prototype applied to the result.

https://github.com/webdriverio/wdio-sync/blob/master/index.js#L197

**Comment by christian-bromann** [comment]
Usually Fibers should not fail. Do you have a use case where it does?

**Comment by billyvg** [comment]
Unfortunately I cannot reproduce it reliably, but it does happen. Specifically, it's the `wait()` that sometimes throws an exception. In my fork I only have `wait()` in the try/catch, and make sure we return the same promise in both cases. https://github.com/Opstarts/wdio-sync/commit/a08f10cc853381f4fbd1b67e8a697e2fd063ce37

**Comment by christian-bromann** [comment]
Without something that reliable can demonstrate the issue I am afraid I have to close this. If you can ensure that your change works and all tests in the framework adapter pass I am happy to merge this.

**Comment by billyvg** [comment]
I'm not familiar with fibers, but there must be a reason why there's a code path that catches the `Can't wait without a fiber` exception and allows execution to continue by returning the promise right?

Because of that, there is definitely the case where the command result does not get prototype.

**Comment by christian-bromann** [comment]
@billyvg it happens for example within WebdriverIO commands, so when a command calls another commands. These are async again and are handled via promises.

**Comment by billyvg** [comment]
At the very least, I'll write to write a test case for this, thanks.
