### ISSUE TITLE
NPM version still does not have last Fibers update

### ISSUE THREAD

**Issue by alcaneo** [webdriverio/wdio-sync#80]
Hello,

When retrieving the last version of this package through NPM, we don't have the fibers@2.0.0
```javascript
"dependencies": {
    "babel-runtime": "6.23.0",
    "fibers": "~1.0.15",
    "object.assign": "^4.0.3"
  },
```

Do I do something wrong or should a new version be uploaded to NPM?

Thanks

**Comment by christian-bromann** [comment]
As per version definition wdio-sync doesn't load fibers v2.0. It doesn't contain any new features.
